# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m'),
        ),
    ]
