# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20170128_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='images/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf'),
        ),
    ]
