# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_auto_20170128_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='image',
        ),
    ]
