# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_remove_usermessage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='add_time',
        ),
    ]
