# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-28 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_auto_20170128_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m'),
        ),
    ]
